name: contentful-hub
desc: contentful-hub
runbooks:
- name: contentful-runbook
  desc: contentful-runbook
  selectors:
  - type: labelSelector
    selector: app=demo
  doc: contentful-runbook.md
- name: runbook-3
  desc: runbook-3
  selectors:
  - type: labelSelector
    selector: app=grafana
  - type: labelSelector
    selector: cluster-id=cbr9a7a2c67e39d7e465ee9ea7e80ddfc5ebd65
  - type: labelSelector
    selector: component=grafana-servers
  - type: labelSelector
    selector: pod-template-hash=689cc5cbff
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=Pod'
  - type: jsonPathSelector
    selector: '{.metadata.name}=grafana-689cc5cbff-chl8g'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=gopaddle-servers'
  doc: runbook-3.md
- name: runbook-4
  desc: runbook-4
  selectors:
  - type: labelSelector
    selector: app=grafana
  - type: labelSelector
    selector: cluster-id=cbr9a7a2c67e39d7e465ee9ea7e80ddfc5ebd65
  - type: labelSelector
    selector: component=grafana-servers
  doc: demo/runbook-4.md
